Repository AY2425S1-CS2103T-F14b-3/tp, pull requests merged in 2024-11, with the labels that each got.

#171 Add person fields to UG and misc
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/CommandTextHistorySequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/MarkSequenceDiagram.puml
  docs/images/CommandTextHistorySequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/MarkSequenceDiagram.png
  src/main/java/seedu/address/logic/Messages.java
Labels: priority.High, alpha-bug

#181 Remove redundant extension in dg
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: alpha-bug

#184 Add profile view in HistoryListPanel
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/HistoryListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ProfileView.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HistoryListPanel.fxml
  src/main/resources/view/ProfileView.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High

#186 Add Use Cases and edit QuickStart
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/JarFileImage.png
  docs/images/MacCmdOpen.jpg
  docs/images/WindowsCmdOpen.png
Labels: priority.High

#187 Update ug screenshots
  docs/UserGuide.md
  docs/images/HelpWindow.png
  docs/images/Ui.png
  docs/images/findAlexDavidResult.png
  docs/images/historyAlice.png
  docs/images/historyRoy.png
Labels: alpha-bug

#198 Fix uncaught exception thrown
  src/main/java/seedu/address/model/contactrecord/ContactRecord.java
  src/test/java/seedu/address/model/contactrecord/ContactRecordTest.java
Labels: priority.High

#267 Fix minor bugs and add planned enhancements
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/test/java/seedu/address/model/contactrecord/ContactRecordTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: priority.High
